version: '3'
services:
    lexicaltranslationcounter:
        image: ltc
        container_name: ltc
        command:
            - /bin/bash
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                LA1: ""
                LA2: ""
        working_dir: /root/
        tty: true
        restart: always
        env_file:
            - ./.env
        environment:
            - LANG=${LANG}
            - LANGUAGE=${LANGUAGE}
            - LC_ALL=${LC_ALL}
            - TZ=${TZ}
            - TERM=${TERM}
        extra_hosts:
            - "host.docker.internal:host-gateway"